language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t gordonwh/docker-react -f Dockerfile.dev .
        
script:
        - docker run -c CI=true gordonwh/docker-react npm run test -- --coverage       
